server:
  port: 8883

spring:
  application:
    name: micro-weather-city-eureka
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/tx-manager?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=true
      username: root
      password: root



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

mybatis:
    type-aliases-package: com.example.gradleDemo.entity
    mapper-locations: classpath:mapper/*.xml