server:
  port: 8888

spring:
  application:
    name: micro-weather-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xieyingge/foo
          search-paths: config-repo
#          basedir:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/